// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaclavikBC.Data;

#nullable disable

namespace VaclavikBC.Migrations
{
    [DbContext(typeof(VaclavikBCContext))]
    partial class VaclavikBCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VaclavikBC.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CalendarConnectionId")
                        .HasColumnType("int");

                    b.Property<string>("ForegroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextSyncToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Selected")
                        .HasColumnType("bit");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarConnectionId");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("VaclavikBC.Models.CalendarConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CalendarConnection");
                });

            modelBuilder.Entity("VaclavikBC.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("RecurrenceRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("CalendarEvent");
                });

            modelBuilder.Entity("VaclavikBC.Models.Calendar", b =>
                {
                    b.HasOne("VaclavikBC.Models.CalendarConnection", "CalendarConnection")
                        .WithMany("Calendars")
                        .HasForeignKey("CalendarConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarConnection");
                });

            modelBuilder.Entity("VaclavikBC.Models.CalendarEvent", b =>
                {
                    b.HasOne("VaclavikBC.Models.Calendar", "Calendar")
                        .WithMany("Events")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VaclavikBC.Models.EventDateTime", "EndInfo", b1 =>
                        {
                            b1.Property<int>("CalendarEventId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<DateTimeOffset?>("DateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("TimeZone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CalendarEventId");

                            b1.ToTable("CalendarEvent");

                            b1.WithOwner()
                                .HasForeignKey("CalendarEventId");
                        });

                    b.OwnsOne("VaclavikBC.Models.EventDateTime", "StartInfo", b1 =>
                        {
                            b1.Property<int>("CalendarEventId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Date")
                                .HasColumnType("datetime2");

                            b1.Property<DateTimeOffset?>("DateTime")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("TimeZone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CalendarEventId");

                            b1.ToTable("CalendarEvent");

                            b1.WithOwner()
                                .HasForeignKey("CalendarEventId");
                        });

                    b.Navigation("Calendar");

                    b.Navigation("EndInfo")
                        .IsRequired();

                    b.Navigation("StartInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("VaclavikBC.Models.Calendar", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("VaclavikBC.Models.CalendarConnection", b =>
                {
                    b.Navigation("Calendars");
                });
#pragma warning restore 612, 618
        }
    }
}
